SHOW USERS;

CREATE OR REPLACE USER TF_DEMO_USER
    RSA_PUBLIC_KEY='YOUR_SF_PUBLIC_KEY'
    DEFAULT_ROLE=PUBLIC
    MUST_CHANGE_PASSWORD=FALSE;

GRANT ROLE SYSADMIN TO USER TF_DEMO_USER;
GRANT ROLE SECURITYADMIN TO USER TF_DEMO_USER;

-- View roles granted to tf-snow
SHOW GRANTS TO USER TF_DEMO_USER;
